<a href="https://colab.research.google.com/github/SimeonHristov99/ML_21-22/blob/main/hello_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Hello, [Tensorflow](https://www.tensorflow.org/api_docs)!

**But what is a tensor?**
 - (for the ML engineer) A tensor is a multidimensional array that can be stored and run on a GPU.
 - (for the mathematician) A generalization of a scalar, vector and matrix:
  - a scalar is a 0D tensor
  - a vector is a 1D tensor
  - a matrix is a 2D tensor

In [ ]:
import tensorflow as tf

**ALWAYS** check the tensorflow version. It gets updated really, REALLY frequently!

In [ ]:
tf.__version__

'2.8.0'

## Initialization of Tensors

### Scalar (0D tensor)

In [ ]:
x = tf.constant(4)
x

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [ ]:
x = tf.constant(4.)
x

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

In [ ]:
x.numpy()

4.0

### Vector (1D tensor)

In [ ]:
x = tf.constant(4, shape=(1))
x

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([4], dtype=int32)>

In [ ]:
x = tf.constant(4, shape=(5))
x

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([4, 4, 4, 4, 4], dtype=int32)>

In [ ]:
x = tf.constant(4, shape=(5), dtype=tf.float32)
x

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([4., 4., 4., 4., 4.], dtype=float32)>

### Matrix (2D tensor)

In [ ]:
x = tf.constant(4, shape=(4, 4))
x

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]], dtype=int32)>

In [ ]:
x = tf.constant([[1, 2, 3], [4, 5, 6]])
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
tf.ones((3, 3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros((3, 3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [ ]:
tf.eye(3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

### Sampling from the standard normal distribution

In [ ]:
tf.random.normal((3, 3), mean=0, stddev=1)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.21536055, -1.0130769 , -0.9780873 ],
       [-1.1212182 , -0.40020323, -1.5368457 ],
       [-0.798981  ,  0.2069086 ,  1.567747  ]], dtype=float32)>

### Sampling from the uniform distribution

In [ ]:
tf.random.uniform((3, 3), minval=0, maxval=1)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.6807418 , 0.69918525, 0.6743777 ],
       [0.10172737, 0.26319385, 0.7737119 ],
       [0.8087901 , 0.19162154, 0.34336448]], dtype=float32)>

### Other useful functions

In [ ]:
tf.range(9)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [ ]:
tf.range(start=5, limit=10)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
x = tf.range(start=1, limit=10, delta=4)
x

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 5, 9], dtype=int32)>

### Casting

In [ ]:
x.dtype

tf.int32

In [ ]:
# Note that x does not change!
# This returns a new tensor.
tf.cast(x, tf.float32)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 5., 9.], dtype=float32)>

## Mathematical Operations

In [ ]:
x = tf.constant([1, 2, 3])
y = tf.constant([9, 8, 7])

### Basic

In [ ]:
x + y

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10], dtype=int32)>

In [ ]:
x - y

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-8, -6, -4], dtype=int32)>

In [ ]:
x * y

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 9, 16, 21], dtype=int32)>

In [ ]:
x / y

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.11111111, 0.25      , 0.42857143])>

In [ ]:
x / 0

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([inf, inf, inf])>

In [ ]:
tf.add(x, y)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10], dtype=int32)>

In [ ]:
tf.subtract(x, y)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-8, -6, -4], dtype=int32)>

In [ ]:
tf.multiply(x, y)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 9, 16, 21], dtype=int32)>

In [ ]:
tf.divide(x, y)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.11111111, 0.25      , 0.42857143])>

In [ ]:
x ** 5

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([  1,  32, 243], dtype=int32)>

### Dot product

In [ ]:
# Here, the `axes` parameter specifies along which axis to
# multiply the elements
tf.tensordot(x, y, axes=1)

<tf.Tensor: shape=(), dtype=int32, numpy=46>

In [ ]:
tf.reduce_sum(x * y)

<tf.Tensor: shape=(), dtype=int32, numpy=46>

### Matrix multiplication

In [ ]:
x = tf.random.normal((2, 3))
y = tf.random.normal((3, 4))

In [ ]:
x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.97646135,  0.79410976,  0.74203026],
       [-1.5870793 , -1.0112021 , -0.8590782 ]], dtype=float32)>

In [ ]:
y

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-1.5068967 , -1.4900901 ,  0.6261724 ,  0.63110805],
       [-1.2087952 , -0.9861452 , -1.6383635 , -0.34983948],
       [-0.6604516 , -0.17339736,  1.9809624 ,  0.6187981 ]],
      dtype=float32)>

In [ ]:
x @ y

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[-2.9214175 , -2.366789  ,  0.78032684,  0.7976086 ],
       [ 4.18128   ,  3.5110455 , -1.0388703 , -1.179456  ]],
      dtype=float32)>

In [ ]:
tf.matmul(x, y)

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[-2.9214175 , -2.366789  ,  0.78032684,  0.7976086 ],
       [ 4.18128   ,  3.5110455 , -1.0388703 , -1.179456  ]],
      dtype=float32)>

## Indexing

In [ ]:
x = tf.constant([0, 1, 1, 2, 3, 1, 2, 3])
x

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([0, 1, 1, 2, 3, 1, 2, 3], dtype=int32)>

In [ ]:
x[:]

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([0, 1, 1, 2, 3, 1, 2, 3], dtype=int32)>

In [ ]:
x[5:]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [ ]:
x[1:3]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 1], dtype=int32)>

In [ ]:
x[::2]

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 3, 2], dtype=int32)>

In [ ]:
x[::-1]

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([3, 2, 1, 3, 2, 1, 1, 0], dtype=int32)>

In [ ]:
indices = tf.constant([0, 3])
tf.gather(x, indices)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 2], dtype=int32)>

In [ ]:
tf.gather(x, [0, 3])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 2], dtype=int32)>

## Reshaping

In [ ]:
x = tf.range(9)
x

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [ ]:
x = tf.reshape(x, (3, 3))
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)>

In [ ]:
tf.reshape(x, -1)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>